export interface BoredApiActivity {
    // Generated by https://quicktype.io
    activity: string;
    accessibility: number;
    type: string;
    participants: number;
    price: number;
    link: string;
    key: number;
}